version: "3.8"

services:
  db:
    image: postgres:14
    container_name: pg_url_shortener
    restart: always
    environment:
      POSTGRES_DB: devdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: url_shortener_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DATABASE_HOST: db # <---- important change from localhost to service name
