version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: urlshortener-db
    restart: always
    environment:
      POSTGRES_DB: urlshortener
      POSTGRES_USER: urluser
      POSTGRES_PASSWORD: urlpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "urluser"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: urlshortener-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: urlshortener
      DB_USER: urluser
      DB_PASSWORD: urlpass
      # Add other environment variables as needed
    ports:
      - "8080:8080"
    restart: always
    # Uncomment if you want to use a .env file
    # env_file:
    #   - .env

volumes:
  pgdata:
